apiVersion: v2
appVersion: "1.0"
description: A Helm chart for et-pet ccd-export application
name: et-pet-ccd-export
home: https://github.com/hmcts/et-pet-ccd-export
version: 0.0.15
dependencies:
  - name: base
    version: 1.4.1
    repository: 'oci://hmctspublic.azurecr.io/helm'
